apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patcher-mwc.fullname" . }}
  labels:
    {{- include "patcher-mwc.labels" . | nindent 4 }}
data:
  # file-like keys
  {{- with .Values.config }}
  config.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
