{{- $ca := genCA "patcher-mwc CA" 365 }}
{{- $CN := (include "patcher-mwc.serviceFQDN" .) }}
{{- $cert := genSignedCert $CN (list "127.0.0.1") (list "localhost" $CN) 365 $ca }}

apiVersion: v1
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "patcher-mwc.fullname" . }}
  labels:
    {{- include "patcher-mwc.labels" . | nindent 4 }}
type: kubernetes.io/tls

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "patcher-mwc.fullname" . }}
webhooks:
  - name: {{ include "patcher-mwc.serviceFQDN" . }}
    clientConfig:
      service:
        name: {{ include "patcher-mwc.fullname" . }}
        namespace: {{ .Release.Namespace | default "default" }}
        path: "/mutate"
      caBundle: {{ $ca.Cert | b64enc | quote }}
    rules:
      {{- with .Values.webhook.rules }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    namespaceSelector:
      {{- with .Values.webhook.namespaceSelector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    objectSelector:
      {{- with .Values.webhook.objectSelector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    #timeoutSeconds: 2
    sideEffects: None
    admissionReviewVersions: ["v1"]
