# Default values for mwc-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

debug: true

image:
  repository: fl64/patcher-mwc
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

serviceAnnotations: {}

webhook:
  failurePolicy: Fail
  rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["internalvirtualizationvirtualmachines"]
  namespaceSelector: {}
  objectSelector: {}
    # matchExpressions:
    #   - key: kubevirt.internal.virtualization.deckhouse.io
    #     operator: "Exists"

config:
  mutations:
  - resource:
      group: internal.virtualization.deckhouse.io
      version: v1
      kind: InternalVirtualizationVirtualMachine
    patches:
    - op: replace
      path: /spec/template/spec/domain/cpu/cores
      value: "7"



resources:
  limits:
    cpu: 20m
    memory: 64Mi
  requests:
    cpu: 20m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
